const questions = [
    "Has sido atrapado tratando de robar un importante libro de la zona restringida de la biblioteca. ¿Qué haces?",
    "La Academia está preparando un exámen que equivale al 50% de la calificación final del año. Tú, por algún motivo inexplicable, no estudiaste nada. ¿Qué haces?",
    "Necesitas obtener información de alguien que no es muy receptivo. ¿Qué haces?",
    "Escoge un número.",
    "Escoge una carta.",
    "Te despiertas y te encuentras en un cuerpo que no es el tuyo. Estás en una habitación con cosas que no reconoces, miras detrás de ti y ves una luz roja brillante en la ventana, que proviene de la luna, la cual está teñida de rojo sangre. Asombrado por el escenario, se cae el libro que ya estaba en tus manos cuando despertaste. ¿Qué haces?",
    "Elige uno:",
    "Tipos de almas: ¿cuál piensas que es tu rol?",
    "Reencarnaste en un mundo de fantasía, sin lazos a tu vida pasada, pero memorias y conocimientos intactos. ¿Cuál sería tu objetivo principal?",
    "Si cometes un error que causa una pérdida, ¿qué pensamientos te vienen a la mente?",
    "Vas de camino a clases tarde y te encuentras con alguien que necesita ayuda, usted:",
    "Se forma un debate en la clase, en el cual, no estás de acuerdo con la opinión mayoritaria de tus compañeros. Tú…",
    "Una flor que demora un siglo en florecer, ha florecido justo en la época que estás viviendo. Está flor está protegida y su uso está restringido solo para el consejo de magia, ya que florecen en poca cantidad. Si sabes que esta flor sirve para potenciar todas las pócimas existentes, tú…",
    "Te encuentras junto a un compañero en una bóveda donde se guardan importantes reliquias mágicas de distintas civilizaciones que ya no existen. En ese momento se presenta una catástrofe en la Academia y no puedes dejar que ciertos objetos se pierdan, pero también tu compañero está en problemas. ¿Qué haces?",
    "¿Qué darías a cambio de lo que tu corazón más desea?",
    "Debes hacer un trabajo grupal, en el cuál el profesor escoge a tus compañeros de equipo. Tú…",
    "¿Qué crees que le da sentido a la vida?",
    "Piensas que…",
    "Sí tuvieras que escoger una frase...",
    "El alma se daña por la falta de...",
    "Escoge una pieza de Ajedrez.",
    "La emoción más longeva y fuerte de la historia de la humanidad es…",
    "Si tuvieras que escoger un camino...",
    "En una orquesta, ¿en qué parte estás?",
    "La esencia del ser humano es…"
]

const answers = [
    ["Huyes, creando una gran ola de caos a tu paso, imposible de seguir y lo suficiente llamativa como para atraer a ojos curiosos que solo verán a quien te descubrió en la escena del crimen",
    "Admites tu error, piensas en una excusa rápida para zafar de la situación y que con algo de suerte no te reporten a dirección",
    "Te mantienes tranquilo, no tomas decisiones precipitadas. Te das cuenta que quién te descubrió es un estudiante, y que no se atreverá a delatarte",
    "Rápidamente empiezas una disputa con quién te ha visto para desviar su atención. Tu principal argumento es que, si tú no debías estar en aquel lugar, esa persona tampoco. Le das a escoger 2 opciones, reportarte a dirección y los dos terminar en problemas, o dejarte ir"],
    ["El que estudia duda de sus conocimientos. Vas con tranquilidad a dar el examen confiando en tu memoria de las clases y que las respuestas llegarán a tu cabeza una vez leas las preguntas.","","",""],
    ["Lo engañas con tus palabras para que te diga exactamente lo que buscas sin que él se dé cuenta.","","",""],
    ["9","","",""],
    ["El Loco","","",""],
    ['Todavía no te recuperas de la confusión. Piensas que todo se trata de un sueño muy vívido, o que algún estudiante te lanzó una pócima de "sueños lúcidos." Te pellizcas el brazo para tratar de despertar, y al no ocurrir nada, decides esperar hasta que despiertes.',"","",""],
    ["LOGOS","","",""],
    ["ARTESANO","","",""],
    ["Ocupar tus conocimientos previos como ventaja para vivir una vida de aventura sin verdaderas consecuencias. Ser el villano si debo serlo, o el héroe sí así me nombra la gente.","","",""],
    ["Debo actuar con rapidez para recuperar mis pérdidas, arriesgando perder el enfoque o retrasar el objetivo. Al final, ¿qué es una buena aventura sin un poco de sorpresas?","","",""],
    ["Te detienes y le preguntas que te ofrece a cambio de tu ayuda. Si es algo que te gusta, lo ayudas. Si no, sigues tu camino.","","",""],
    ["Tus compañeros están en lo correcto, pero decides persuadirlos para que estén de acuerdo contigo.","","",""],
    ["Te infiltras en el campo de flores y robas 10 flores. Sabes que cada flor tiene 20 pétalos y solo basta 1 para crear las más poderosas pociones. Planeas vender aquellas que no vas a ocupar en el mercado negro.","","",""],
    ["No me preocupo por ninguno de los dos, solo veo por mí mismo y mi propia seguridad.","","",""],
    ["Lo que puedo permitirme perder.","","",""],
    ["Sabes que puedes hacer un trabajo mejor si estás solo. No te importa que ya haya un líder y haces lo que te dé la gana con el trabajo.","","",""],
    ["Dándole a tu vida un toque creativo de música, arte o literatura. Quizás un poco de aventura por aquí y por allá, ¡es la mejor manera de darle sentido a tu vida!","","",""],
    ["El país es fuerte porque la gente es libre.","","",""],
    ["Y los que fueron vistos bailando, fueron considerados locos por aquellos que no podían escuchar la música.","","",""],
    ["Coraje","","",""],
    ["El Caballo","","",""],
    ["Sorpresa","","",""],
    ["CINISMO: Se caracteriza por el rechazo de los convencionalismos sociales y de la moral comúnmente admitida.","","",""],
    ["En el público","","",""],
    ["Su sexto sentido","","",""],
]

const answerValue = [
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
    [ [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ],
]